### ISSUE TITLE
Documentación 1

### ISSUE THREAD

**Issue by yamideus** [yamideus/Pacto_de_Honor#1]
- [x] Requerimientos IEEE 830 @yamideus                        
- [x] Canvas @CristianGarzonBernal                        
- [x] Story mapping @yamideus                        
- [x] Release planning @yamideus
